# The following special comment enables IDE intellisense for this config file.
# It requires you to have the Yaml Language Server available, but it is likely
# the case if you're using any modern IDE (VSCode, Webstorm, Neovim, etc).
# yaml-language-server: $schema=https://yarnpkg.com/configuration/yarnrc.json

nodeLinker: node-modules
